### ISSUE TITLE
Can't get it working on FreeBSD 13

### ISSUE THREAD

**Issue by v20z** [heiher/hev-fsh#1]
Hello **_heiner_**.

I'm trying `fsh` on FreeBSD 13 with simplest scenario but unable to succeed.

On gateway (192.168.0.1):
```
# ./hev-fsh -4 -s
```
On forwarder (192.168.0.251):
```
# ./hev-fsh -4 -f 192.168.0.1
```
On connector (192.168.0.200) (token from server):
```
# ./hev-fsh -4 -p 22000:127.0.0.1:22 192.168.0.1/5cf08619-bc22-4473-8668-84197993bf1b

# sockstat -4 | grep :22000
root     hev-fsh    49793 5  tcp4   127.0.0.1:22000       *:*

# ssh -vvvv 127.0.0.1 -p 22000
OpenSSH_7.5p1, OpenSSL 1.0.2p-freebsd  14 Aug 2018
debug1: Reading configuration data /etc/ssh/ssh_config
debug3: /etc/ssh/ssh_config line 50: Including file /etc/opt/openssh/local/ssh_config depth 0
debug1: Reading configuration data /etc/opt/openssh/local/ssh_config
debug2: resolving "127.0.0.1" port 22000
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 127.0.0.1 [127.0.0.1] port 22000.
debug1: Connection established.
...
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.5 FreeBSD-20170903
debug1: ssh_exchange_identification: ^@^@^A^@^@^@^@^@^@^@^@^@^@^@^@SSH-2.0-OpenSSH_7.5 FreeBSD-20170903

debug1: ssh_exchange_identification:

ssh_exchange_identification: Connection closed by remote host
```
What do you advice to see more?

Thank You.

**Comment by heiher** [comment]
> Hello heiner.
> 
> I'm trying `fsh` on FreeBSD 13 with simplest scenario but unable to succeed.
> 
> On gateway (192.168.0.1):
> 
> ```
> # ./hev-fsh -4 -s
> ```
> 
> On forwarder (192.168.0.251):
> 
> ```
> # ./hev-fsh -4 -f 192.168.0.1
> ```

```
# ./hev-fsh -4 -f -p 192.168.0.1
```

**Comment by v20z** [comment]
Dear **_heiner_**, thanks for the lightning-fast answer.

Aw, my mistake. I was completely inattentive and too hasty. Sorry to be annoying,  and yes, that way everything works as intended.

One more questions. Is there a way to see some statistics on the server?,  List of connected forwarders and connector clients except to look at logs and watching connected ports? Reset/disconnect some selected yet connected client, for example to initiate it reconnection ?

I appreciate your attention. Thank You.

**Comment by heiher** [comment]
Currently there is no real-time management functions, only log. :smile:

**Comment by v20z** [comment]
Ok, well, that's good too. Let's hope that such features will appear in the next versions. Please continue development, your software is interesting. Thanks for communication. It looks like this issue has been solved.

 Thank You.

**Comment by heiher** [comment]
If it is implemented in the future, I will @ you.
